### ISSUE TITLE
Does this package works with Queuing Mail

### ISSUE THREAD

**Issue by ssatz** [ElfSundae/laravel-switchable-mail#2]
Does this package works with Queuing Mail

**Comment by ElfSundae** [comment]
Yes, it works.

**Comment by ssatz** [comment]
thanks. Let me try it with Laravel 5.4 hope it works

**Comment by ElfSundae** [comment]
This package is only compatible with Laravel 5.3, but the extending thought works on L54. You may compare `MailServiceProvider` and `Mail` classes between Laravel framework and this package, then write your own multi mail package.
